# Read the Docs configuration file
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  apt_packages:
    - doxygen
    - graphviz
  # Custom commands for building documentation
  commands:
    - make docs

python:
  version: "3.8"
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
