version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    doxygen: "1.9.1" # You can specify a Doxygen version
  jobs:
    pre_build:
      # Create the Doxygen output directory if it doesn't exist
      - mkdir -p docs/doxygen/xml
      # Generate Doxygen XML output
      - doxygen Doxyfile

sphinx:
  configuration: docs/conf.py

# Optional: Specify Python requirements if you have them
python:
  install:
    - requirements: docs/requirements.txt
