name: CI & Release

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # modest parallelism to reduce wall time (and minutes)
  MAKEFLAGS: -j2

jobs:
  # Fast, cheap PR signal (Ubuntu only). Also runs on tags so we reuse artifacts.
  build-core:
    name: Build & Test (ubuntu-latest.x64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y clang make flex bison zip unzip ccache

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ccache-linux-${{ hashFiles('Makefile', 'src/**/*.c', 'src/**/*.h', 'tests/**/*.c', 'tests/**/*.h') }}
          restore-keys: |
            ccache-linux-

      - name: Build & test (Ubuntu)
        run: |
          set -euxo pipefail
          ccache --zero-stats || true
          make clean
          make test CC="ccache clang"
          make lib/libOCTypes.so CC="ccache clang"
          cp lib/libOCTypes.so libOCTypes.so
          cp lib/libOCTypes.a  libOCTypes.a
          ccache --show-stats || true

      # Only package headers on the canonical build (saves time elsewhere)
      - name: Package public headers
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          set -euxo pipefail
          mkdir -p header-pkg/include
          cp src/*.h header-pkg/include/
          zip -j header-pkg/libOCTypes-headers.zip header-pkg/include/*.h

      # Upload artifacts only for releases
      - name: Upload Ubuntu artifacts (tag only)
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: libOCTypes-ubuntu-latest.x64
          path: |
            libOCTypes.a
            libOCTypes.so
          compression-level: 9
          if-no-files-found: error

      - name: Upload headers (tag only)
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: libOCTypes-headers
          path: header-pkg/libOCTypes-headers.zip
          compression-level: 9

  # macOS and Windows only on tags (keeps PR minutes low)
  build-macos:
    if: startsWith(github.ref, 'refs/tags/')
    name: Build & Test (macos-latest)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Install deps
        run: |
          brew update
          brew install flex bison ccache
          echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH
          echo "$(brew --prefix flex)/bin"  >> $GITHUB_PATH

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ccache-macos-${{ hashFiles('Makefile', 'src/**/*.c', 'src/**/*.h', 'tests/**/*.c', 'tests/**/*.h') }}
          restore-keys: |
            ccache-macos-

      - name: Build & test (macOS)
        run: |
          set -euxo pipefail
          ccache --zero-stats || true
          make clean
          make test CC="ccache clang"
          make lib/libOCTypes.dylib CC="ccache clang"
          cp lib/libOCTypes.dylib libOCTypes.dylib
          cp lib/libOCTypes.a     libOCTypes.a
          ccache --show-stats || true

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libOCTypes-macos-latest
          path: |
            libOCTypes.a
            libOCTypes.dylib
          compression-level: 9
          if-no-files-found: error

  build-windows:
    if: startsWith(github.ref, 'refs/tags/')
    name: Build & Test (windows-latest)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Set up MSYS2 & MinGW
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          cache: true
          install: >
            mingw-w64-x86_64-toolchain
            make
            flex
            bison
            mingw-w64-x86_64-ccache

      - name: Cache ccache (MSYS2)
        uses: actions/cache@v4
        with:
          path: C:\Users\runneradmin\.ccache
          key: ccache-windows-${{ hashFiles('Makefile', 'src/**/*.c', 'src/**/*.h', 'tests/**/*.c', 'tests/**/*.h') }}
          restore-keys: |
            ccache-windows-

      - name: Build & test (Windows)
        shell: msys2 {0}
        run: |
          set -euxo pipefail
          ccache --zero-stats || true
          make clean
          make test CC="ccache gcc" \
               CFLAGS="-std=c99 -I. -Isrc -O3 -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers" \
               LEX=flex YACC="bison"
          make lib/libOCTypes.dll CC="ccache gcc" \
               CFLAGS="-std=c99 -I. -Isrc -O3 -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers" \
               LEX=flex YACC="bison"
          cp lib/libOCTypes.a    libOCTypes.a
          cp lib/libOCTypes.dll  libOCTypes.dll
          cp lib/libOCTypes.dll.a libOCTypes.dll.a
          ccache --show-stats || true

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libOCTypes-windows-latest
          path: |
            libOCTypes.a
            libOCTypes.dll
            libOCTypes.dll.a
          compression-level: 9
          if-no-files-found: error

  # ARM64 Linux only on tags (as you had)
  build-arm64:
    if: startsWith(github.ref, 'refs/tags/')
    name: Build & Test (ubuntu-latest.arm64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64

      - name: Build & test in ARM64 container
        run: |
          set -euxo pipefail
          docker run --rm --platform=linux/arm64 \
            -v ${{ github.workspace }}:/src -w /src ubuntu:22.04 bash -lc "\
              apt-get update && apt-get install -y clang make flex bison unzip && \
              make clean && make test CC=clang && \
              make lib/libOCTypes.so CC=clang && \
              cp lib/libOCTypes.a libOCTypes.a && \
              cp lib/libOCTypes.so libOCTypes.so"

      - name: Upload ARM64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libOCTypes-ubuntu-latest.arm64
          path: |
            libOCTypes.a
            libOCTypes.so
          compression-level: 9
          if-no-files-found: error

  release:
    if: startsWith(github.ref, 'refs/tags/')
    name: Package & Release
    needs: [build-core, build-macos, build-windows, build-arm64]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install zip
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          path: artifacts

      - name: Copy header bundle
        run: |
          mkdir -p packages
          cp artifacts/libOCTypes-headers/libOCTypes-headers.zip packages/

      - name: Package libraries into ZIPs
        run: |
          set -euxo pipefail
          mkdir -p packages
          for osdir in artifacts/*; do
            [ -d "$osdir" ] || continue
            base="$(basename "$osdir")"
            platform="${base#libOCTypes-}"
            [ "$platform" = "headers" ] && continue
            files=( "$osdir"/libOCTypes.* )
            found=0
            for f in "${files[@]}"; do [ -f "$f" ] && found=1 && break; done
            [ $found -eq 1 ] || { echo "Skipping $osdir (no library files)"; continue; }
            zip -j "packages/libOCTypes-${platform}.zip" "${files[@]}"
          done

      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: packages/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          