name: CI & Release

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build & Test (${{ matrix.label }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
            label: ubuntu-latest.x64
          - os: ubuntu-latest
            arch: arm64
            label: ubuntu-latest.arm64
          - os: macos-latest
            arch: x64
            label: macos-latest
          - os: windows-latest
            arch: x64
            label: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build & test on Linux/macOS
        if: runner.os != 'Windows' && matrix.arch == 'x64'
        run: |
          make clean
          make test-asan
          # Build shared library
          if [ "$(uname)" = "Darwin" ]; then
            make lib/libOCTypes.dylib
            cp lib/libOCTypes.dylib libOCTypes.dylib
          else
            make lib/libOCTypes.so
            cp lib/libOCTypes.so libOCTypes.so
          fi
          cp lib/libOCTypes.a libOCTypes.a
      # ARM64 Linux build in QEMU container
      - name: Set up QEMU emulation
        if: matrix.arch == 'arm64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64
      - name: Install QEMU binfmt handlers
        if: matrix.arch == 'arm64'
        run: |
          docker run --rm --privileged tonistiigi/binfmt --install all
      - name: Build & test in ARM64 container
        if: matrix.arch == 'arm64'
        run: |
          docker run --rm --platform=linux/arm64 \
            -v ${{ github.workspace }}:/src -w /src ubuntu:22.04 bash -lc "\
              apt-get update && apt-get install -y clang make flex bison unzip && \
              make clean && make test && \
              make lib/libOCTypes.so && \
              cp lib/libOCTypes.a libOCTypes.a && \
              cp lib/libOCTypes.so libOCTypes.so"
      - name: Set up MSYS2 & MinGW (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: |
            mingw-w64-x86_64-toolchain
            make
            flex
            bison

      - name: Build & test on Windows
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          make clean
          make test CC=gcc \
               CFLAGS="-std=c99 -I. -Isrc -O3 -Wall -Wextra \
                       -Wno-sign-compare -Wno-unused-parameter \
                       -Wno-missing-field-initializers" \
               LEX=flex YACC="bison"
          # Build shared library (DLL)
          make lib/libOCTypes.dll CC=gcc \
               CFLAGS="-std=c99 -I. -Isrc -O3 -Wall -Wextra \
                       -Wno-sign-compare -Wno-unused-parameter \
                       -Wno-missing-field-initializers" \
               LEX=flex YACC="bison"
          cp lib/libOCTypes.a libOCTypes.a
          cp lib/libOCTypes.dll libOCTypes.dll
          cp lib/libOCTypes.dll.a libOCTypes.dll.a

      - name: Upload library artifact
        uses: actions/upload-artifact@v4
        with:
          name: libOCTypes-${{ matrix.label }}
          path: |
            libOCTypes.a
            libOCTypes.so
            libOCTypes.dylib
            libOCTypes.dll
            libOCTypes.dll.a

      # Package & upload public headers on Ubuntu only
      - name: Package public headers
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'x64'
        run: |
          mkdir -p header-pkg/include
          cp src/*.h header-pkg/include/
          zip -j header-pkg/libOCTypes-headers.zip header-pkg/include/*.h
      - name: Upload headers artifact
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'x64'
        uses: actions/upload-artifact@v4
        with:
          name: libOCTypes-headers
          path: header-pkg/libOCTypes-headers.zip

  release:
    name: Package & Release
    needs: [build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          path: artifacts

      # Copy the header bundle into the packages folder
      - name: Copy header bundle
        run: |
          mkdir -p packages
          cp artifacts/libOCTypes-headers/libOCTypes-headers.zip packages/

      - name: Package libraries into ZIPs
        run: |
          mkdir -p packages
          for osdir in artifacts/*; do
            if [ ! -d "$osdir" ]; then
              continue
            fi

            os=$(basename "$osdir")
            # Strip the libOCTypes- prefix to get clean platform name
            platform=${os#libOCTypes-}

            # Skip header artifacts
            if [[ "$platform" == "headers" ]]; then
              continue
            fi

            zipfile="packages/libOCTypes-${platform}.zip"

            # Find all library files and package them
            files_to_zip=()
            for lib in "${osdir}"/libOCTypes.*; do
              if [ -f "$lib" ]; then
                files_to_zip+=("$lib")
              fi
            done

            if [ ${#files_to_zip[@]} -eq 0 ]; then
              echo "Skipping $osdir (no library files to package)"
              continue
            fi

            if [[ "$platform" == windows-latest ]]; then
              # Use PowerShell for Windows
              file_list=$(printf "'%s'," "${files_to_zip[@]}")
              file_list=${file_list%,}  # Remove trailing comma
              pwsh -Command "Compress-Archive -Path ${file_list} -DestinationPath '${zipfile}'"
            else
              # Use zip for Unix-like systems
              zip -j "${zipfile}" "${files_to_zip[@]}"
            fi
          done

      - name: Create or update GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: packages/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
