name: C/C++ Library CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Ensure 'make' is available on Windows
      - name: Install make on Windows
        if: runner.os == 'Windows'
        run: choco install make -y

      - name: Build with Makefile
        run: |
          make clean
          make

      - name: Verify library
        run: |
          echo "Built library:"
          ls -l libOCTypes.a
