name: C/C++ Library CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and test on Linux/macOS
        if: runner.os != 'Windows'
        run: |
          make clean
          make test-asan

      # Windows specific steps using MinGW
      - name: Set up MSYS2 and MinGW
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            make
            flex
            bison

      - name: Build on Windows with MinGW
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          make clean
          make CC=gcc CFLAGS="-std=c99 -I . -I src -O3 -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers" LEX=flex YACC="bison -y"

      - name: Verify library (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0} # Use msys2 shell for ls consistency
        run: |
          echo "Built library (Windows):"
          ls -l libOCTypes.a
      - name: Verify library (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          echo "Built library (Linux/macOS):"
          ls -l libOCTypes.a
