name: C/C++ Library CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install make and WinFlexBison on Windows
        if: runner.os == 'Windows'
        shell: powershell
        run: choco install make winflexbison3 -y

      - name: Refresh environment variables
        if: runner.os == 'Windows'
        shell: cmd
        run: refreshenv

      - name: Build and test on Linux/macOS
        if: runner.os != 'Windows'
        run: |
          make clean
          make test

      - name: Build on Windows
        if: runner.os == 'Windows'
        run: |
          make clean
          # Use .exe extensions for executables on Windows
          make LEX=win_flex.exe YACC="win_bison.exe -y"

      - name: Verify library
        run: |
          echo "Built library:"
          ls -l libOCTypes.a
